import React from "react";
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: "#18181b",
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#e4e4e7",
    paddingBottom: 16,
  },
  title: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: "#71717a",
  },
  coachLine: {
    fontSize: 9,
    color: "#a1a1aa",
    marginTop: 4,
  },
  mealSection: {
    marginBottom: 16,
  },
  mealHeader: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase" as const,
    letterSpacing: 0.8,
    color: "#3f3f46",
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#d4d4d8",
  },
  itemRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    paddingVertical: 3,
    paddingHorizontal: 4,
  },
  itemRowAlt: {
    backgroundColor: "#fafafa",
  },
  foodName: {
    fontSize: 10,
    flex: 1,
  },
  portion: {
    fontSize: 10,
    color: "#52525b",
    textAlign: "right" as const,
    maxWidth: 160,
  },
  emptyState: {
    textAlign: "center" as const,
    color: "#a1a1aa",
    fontSize: 12,
    marginTop: 60,
  },
  footer: {
    position: "absolute" as const,
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    borderTopWidth: 0.5,
    borderTopColor: "#e4e4e7",
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: "#a1a1aa",
  },
});

export type MealPlanPdfItem = {
  mealName: string;
  foodName: string;
  quantity: string;
  unit: string;
  servingDescription: string | null;
};

export type MealPlanPdfData = {
  clientName: string;
  coachName?: string;
  weekLabel?: string;
  items: MealPlanPdfItem[];
};

export async function renderMealPlanPdf(data: MealPlanPdfData): Promise<Buffer> {
  return renderToBuffer(<MealPlanPdfDocument data={data} />) as Promise<Buffer>;
}

function MealPlanPdfDocument({ data }: { data: MealPlanPdfData }) {
  const { clientName, coachName, weekLabel, items } = data;

  // Group items by meal name
  const grouped = new Map<string, MealPlanPdfItem[]>();
  for (const item of items) {
    const key = item.mealName || "Untitled Meal";
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(item);
  }

  const isEmpty = items.length === 0;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Meal Plan</Text>
          <Text style={styles.subtitle}>
            {clientName}
            {weekLabel ? ` — Week of ${weekLabel}` : ""}
          </Text>
          {coachName && (
            <Text style={styles.coachLine}>Coach: {coachName}</Text>
          )}
        </View>

        {/* Content */}
        {isEmpty ? (
          <Text style={styles.emptyState}>
            No items in this meal plan yet. Check back with your coach.
          </Text>
        ) : (
          Array.from(grouped).map(([mealName, mealItems]) => (
            <View key={mealName} style={styles.mealSection} wrap={false}>
              <Text style={styles.mealHeader}>{mealName}</Text>
              {mealItems.map((item, i) => {
                const portion = item.servingDescription
                  ? item.servingDescription
                  : item.quantity && item.unit
                    ? `${item.quantity} ${item.unit}`
                    : "\u2014";

                return (
                  <View
                    key={`${item.foodName}-${i}`}
                    style={i % 2 === 1 ? [styles.itemRow, styles.itemRowAlt] : styles.itemRow}
                  >
                    <Text style={styles.foodName}>{item.foodName}</Text>
                    <Text style={styles.portion}>{portion}</Text>
                  </View>
                );
              })}
            </View>
          ))
        )}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>
            Generated by Steadfast (Beta)
          </Text>
          <Text style={styles.footerText}>
            {new Date().toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </Text>
        </View>
      </Page>
    </Document>
  );
}
